// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDigitalLibrary.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyDigitalLibrary.Infrastructure.Migrations
{
    [DbContext(typeof(MyDigitalLibraryDbContext))]
    [Migration("20260911142956_AddManualFieldOverrides")]
    partial class AddManualFieldOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("integer")
                        .HasColumnName("death_year");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<string>("SortName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("sort_name");

                    b.Property<string>("_externalIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("external_ids");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.HasIndex("SortName")
                        .HasDatabaseName("ix_authors_sort_name");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.Bookstore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdapterKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("adapter_key");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_bookstores");

                    b.HasIndex("AdapterKey")
                        .IsUnique()
                        .HasDatabaseName("ix_bookstores_adapter_key");

                    b.ToTable("bookstores", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.BookstoreListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<Guid>("BookstoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookstore_id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_bookstore_listings");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_bookstore_listings_edition_id");

                    b.HasIndex("LastCheckedAt")
                        .HasDatabaseName("ix_bookstore_listings_last_checked_at");

                    b.ToTable("bookstore_listings", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cover_image_url");

                    b.Property<int>("CoverType")
                        .HasColumnType("integer")
                        .HasColumnName("cover_type");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("FieldOverrides")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_overrides");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("Isbn13")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn13");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Narrator")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("narrator");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("Publisher")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("publisher");

                    b.Property<string>("Translator")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("translator");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_editions");

                    b.HasIndex("Isbn13")
                        .IsUnique()
                        .HasDatabaseName("ix_editions_isbn13")
                        .HasFilter("isbn13 IS NOT NULL");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_editions_work_id");

                    b.ToTable("editions", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_genre_id");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("ParentGenreId")
                        .HasDatabaseName("ix_genres_parent_genre_id");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FieldOverrides")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_overrides");

                    b.Property<int?>("FirstPublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("first_publication_year");

                    b.PrimitiveCollection<Guid[]>("GenreIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("genre_ids");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_title");

                    b.Property<decimal?>("PositionInSeries")
                        .HasColumnType("numeric")
                        .HasColumnName("series_position");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_works");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_works_series_id");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_file_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_import_jobs_user_id_status");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.LibraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("PersonalNote")
                        .HasColumnType("text")
                        .HasColumnName("personal_note");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_library_items");

                    b.HasIndex("UserId", "Status", "Format")
                        .HasDatabaseName("ix_library_items_user_id_status_format");

                    b.ToTable("library_items", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("borrower_name");

                    b.Property<DateOnly>("LentOn")
                        .HasColumnType("date")
                        .HasColumnName("lent_on");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_item_id");

                    b.Property<DateOnly?>("ReturnedOn")
                        .HasColumnType("date")
                        .HasColumnName("returned_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_loans");

                    b.HasIndex("LibraryItemId")
                        .HasDatabaseName("ix_loans_library_item_id");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_item_id");

                    b.Property<string>("LocationInBook")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location_in_book");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("LibraryItemId")
                        .HasDatabaseName("ix_notes_library_item_id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PageOrPosition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("page_or_position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_quotes_work_id");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.ReadingGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("TargetBooks")
                        .HasColumnType("integer")
                        .HasColumnName("target_books");

                    b.Property<int?>("TargetPages")
                        .HasColumnType("integer")
                        .HasColumnName("target_pages");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_reading_goals");

                    b.HasIndex("UserId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_reading_goals_user_id_year");

                    b.ToTable("reading_goals", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("UserId", "WorkId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_user_id_work_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_shelves");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_shelves_user_id_name");

                    b.ToTable("shelves", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_user_id_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.WishlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AddedOn")
                        .HasColumnType("date")
                        .HasColumnName("added_on");

                    b.Property<int>("DesiredFormat")
                        .HasColumnType("integer")
                        .HasColumnName("desired_format");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fulfilled");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("PreferredEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_edition_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_entries");

                    b.HasIndex("UserId", "IsFulfilled")
                        .HasDatabaseName("ix_wishlist_entries_user_id_is_fulfilled");

                    b.ToTable("wishlist_entries", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.WorkRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_work_ratings");

                    b.HasIndex("UserId", "WorkId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_ratings_user_id_work_id");

                    b.ToTable("work_ratings", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Reading.ProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ReadingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_session_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("_kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int?>("_pageValue")
                        .HasColumnType("integer")
                        .HasColumnName("page_value");

                    b.Property<decimal?>("_percentValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percent_value");

                    b.Property<long?>("_positionTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("position_ticks");

                    b.HasKey("Id")
                        .HasName("pk_reading_progress");

                    b.HasIndex("ReadingSessionId")
                        .HasDatabaseName("ix_reading_progress_reading_session_id");

                    b.ToTable("reading_progress", null, t =>
                        {
                            t.HasCheckConstraint("ck_reading_progress_single_value", "(kind = 'page' AND page_value IS NOT NULL AND percent_value IS NULL AND position_ticks IS NULL)\nOR (kind = 'percent' AND percent_value IS NOT NULL AND page_value IS NULL AND position_ticks IS NULL)\nOR (kind = 'timestamp' AND position_ticks IS NOT NULL AND page_value IS NULL AND percent_value IS NULL)");
                        });
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Reading.ReadingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AbandonReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("abandon_reason");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_item_id");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reading_sessions");

                    b.HasIndex("UserId", "LibraryItemId")
                        .HasDatabaseName("ix_reading_sessions_user_id_library_item_id");

                    b.ToTable("reading_sessions", (string)null);
                });

            modelBuilder.Entity("MyDigitalLibrary.Infrastructure.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MyDigitalLibrary.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MyDigitalLibrary.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MyDigitalLibrary.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.BookstoreListing", b =>
                {
                    b.OwnsOne("MyDigitalLibrary.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("BookstoreListingId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("BookstoreListingId");

                            b1.ToTable("bookstore_listings");

                            b1.WithOwner()
                                .HasForeignKey("BookstoreListingId")
                                .HasConstraintName("fk_bookstore_listings_bookstore_listings_id");
                        });

                    b.OwnsMany("MyDigitalLibrary.Domain.Catalog.PriceHistoryEntry", "PriceHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid")
                                .HasColumnName("listing_id");

                            b1.Property<DateTimeOffset>("ObservedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("observed_at");

                            b1.HasKey("Id")
                                .HasName("pk_bookstore_listing_price_history");

                            b1.HasIndex("ListingId")
                                .HasDatabaseName("ix_bookstore_listing_price_history_listing_id");

                            b1.ToTable("bookstore_listing_price_history", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ListingId")
                                .HasConstraintName("fk_bookstore_listing_price_history_bookstore_listings_listing_");

                            b1.OwnsOne("MyDigitalLibrary.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("PriceHistoryEntryId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("PriceHistoryEntryId");

                                    b2.ToTable("bookstore_listing_price_history");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceHistoryEntryId")
                                        .HasConstraintName("fk_bookstore_listing_price_history_bookstore_listing_price_his");
                                });

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.Navigation("Price");

                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.Genre", b =>
                {
                    b.HasOne("MyDigitalLibrary.Domain.Catalog.Genre", null)
                        .WithMany()
                        .HasForeignKey("ParentGenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_genres_genres_parent_genre_id");
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Catalog.Work", b =>
                {
                    b.OwnsMany("MyDigitalLibrary.Domain.Catalog.WorkAuthor", "Authors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid")
                                .HasColumnName("author_id");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.Property<Guid>("WorkId")
                                .HasColumnType("uuid")
                                .HasColumnName("work_id");

                            b1.HasKey("Id")
                                .HasName("pk_work_authors");

                            b1.HasIndex("AuthorId")
                                .HasDatabaseName("ix_work_authors_author_id");

                            b1.HasIndex("WorkId")
                                .HasDatabaseName("ix_work_authors_work_id");

                            b1.ToTable("work_authors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkId")
                                .HasConstraintName("fk_work_authors_works_work_id");
                        });

                    b.Navigation("Authors");
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.ImportJob", b =>
                {
                    b.OwnsOne("MyDigitalLibrary.Domain.Library.ImportJobStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("ImportJobId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("FailedRows")
                                .HasColumnType("integer")
                                .HasColumnName("stats_failed_rows");

                            b1.Property<int>("SucceededRows")
                                .HasColumnType("integer")
                                .HasColumnName("stats_succeeded_rows");

                            b1.Property<int>("TotalRows")
                                .HasColumnType("integer")
                                .HasColumnName("stats_total_rows");

                            b1.HasKey("ImportJobId");

                            b1.ToTable("import_jobs");

                            b1.WithOwner()
                                .HasForeignKey("ImportJobId")
                                .HasConstraintName("fk_import_jobs_import_jobs_id");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.LibraryItem", b =>
                {
                    b.OwnsOne("MyDigitalLibrary.Domain.ValueObjects.Acquisition", "Acquisition", b1 =>
                        {
                            b1.Property<Guid>("LibraryItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("AcquiredOn")
                                .HasColumnType("date")
                                .HasColumnName("acquired_on");

                            b1.Property<int>("Method")
                                .HasColumnType("integer")
                                .HasColumnName("acquisition_method");

                            b1.Property<string>("Source")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("acquisition_source");

                            b1.HasKey("LibraryItemId");

                            b1.ToTable("library_items");

                            b1.WithOwner()
                                .HasForeignKey("LibraryItemId")
                                .HasConstraintName("fk_library_items_library_items_id");

                            b1.OwnsOne("MyDigitalLibrary.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("AcquisitionLibraryItemId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("acquisition_price_amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("acquisition_price_currency");

                                    b2.HasKey("AcquisitionLibraryItemId");

                                    b2.ToTable("library_items");

                                    b2.WithOwner()
                                        .HasForeignKey("AcquisitionLibraryItemId")
                                        .HasConstraintName("fk_library_items_library_items_id");
                                });

                            b1.Navigation("Price");
                        });

                    b.OwnsOne("MyDigitalLibrary.Domain.ValueObjects.PhysicalLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("LibraryItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Box")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location_box");

                            b1.Property<string>("Room")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location_room");

                            b1.Property<string>("Shelf")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location_shelf");

                            b1.HasKey("LibraryItemId");

                            b1.ToTable("library_items");

                            b1.WithOwner()
                                .HasForeignKey("LibraryItemId")
                                .HasConstraintName("fk_library_items_library_items_id");
                        });

                    b.Navigation("Acquisition")
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.Shelf", b =>
                {
                    b.OwnsMany("MyDigitalLibrary.Domain.Library.ShelfItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("AddedOn")
                                .HasColumnType("date")
                                .HasColumnName("added_on");

                            b1.Property<Guid>("LibraryItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("library_item_id");

                            b1.Property<Guid>("ShelfId")
                                .HasColumnType("uuid")
                                .HasColumnName("shelf_id");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer")
                                .HasColumnName("sort_order");

                            b1.HasKey("Id")
                                .HasName("pk_shelf_items");

                            b1.HasIndex("ShelfId", "LibraryItemId")
                                .IsUnique()
                                .HasDatabaseName("ix_shelf_items_shelf_id_library_item_id");

                            b1.ToTable("shelf_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShelfId")
                                .HasConstraintName("fk_shelf_items_shelves_shelf_id");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Library.WishlistEntry", b =>
                {
                    b.OwnsOne("MyDigitalLibrary.Domain.ValueObjects.Money", "MaxPrice", b1 =>
                        {
                            b1.Property<Guid>("WishlistEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("max_price_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("max_price_currency");

                            b1.HasKey("WishlistEntryId");

                            b1.ToTable("wishlist_entries");

                            b1.WithOwner()
                                .HasForeignKey("WishlistEntryId")
                                .HasConstraintName("fk_wishlist_entries_wishlist_entries_id");
                        });

                    b.Navigation("MaxPrice");
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Reading.ProgressEntry", b =>
                {
                    b.HasOne("MyDigitalLibrary.Domain.Reading.ReadingSession", null)
                        .WithMany("Progress")
                        .HasForeignKey("ReadingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progress_reading_sessions_reading_session_id");
                });

            modelBuilder.Entity("MyDigitalLibrary.Domain.Reading.ReadingSession", b =>
                {
                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
